jobs:
- name: build-jekyll
  public: true
  plan:
  - get: git-pr
    trigger: true
    version: every
  - get: gist
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: praqma/gh-pages}
      inputs: 
        - name: git-pr
        - name: gist
      outputs: 
        - name: site
      run:
        path: sh
        args:
        - -exc
        - |
           git clone gist site
           cd git-pr && jekyll build && cp _site/* ../site && cd ../site
           git config --global user.email "nobody@special.praqma"
           git config --global user.name "praqma" && git add .           
  - put: gist
    params: 
      repository: site


- name: test-site
  public: true
  plan: 
  - get: repository
    trigger: true
  - task: curl-site
    config: 
      platform: linux
      image_resource: 
        type: docker-image
        source: 
          repository: praqma/gh-pages
      run: 
        path: sh
        args: 
        - -exc
        - |
          apt-get update
          apt-get install -y curl
          curl https://bl.ocks.org/sharor/raw/4b2015849c31bfb860c6a021ba9ed63a/
    on_failure:
      put: slack-alert
      params:
        channel: '#general'
        text: |
          The build failed. Please go correct it at:
          http://192.168.100.4:8080//teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          http://192.168.100.4:8080//builds/$BUILD_ID
  - task: link-checker
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: praqma/linkchecker}
      run:
        path: sh
        args:
        - -exc
        - |
          linkchecker http://bl.ocks.org/sharor/raw/4b2015849c31bfb860c6a021ba9ed63a/
    on_failure:
      put: slack-alert
      params:
        channel: '#general'
        text: |
          The build failed. Please go correct it at:
          http://192.168.100.4:8080//teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          http://192.168.100.4:8080//builds/$BUILD_ID
- name: update-production-site
  public: true
  plan:
  - get: repository
    passed: [test-site]
  - put: github-pages
    params:
      repository: repository
      force: true
  
resources: 
- name: repository
  type: git
  source:
    uri: https://github.com/Sharor/concourse-workshop.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: git-pr
  type: pull-request
  source:
    access_token: {{concourse-pull-request-token}}
    private_key: {{concourse-token}}
    repo: Sharor/concourse-workshop
    base: master

  type: git
  source:
    uri: https://github.com/Sharor/concourse-workshop.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: gist
  type: git 
  source: 
    uri: https://gist.github.com/4b2015849c31bfb860c6a021ba9ed63a.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: github-pages
  type: git
  source: 
    uri: https://github.com/Sharor/concourse-workshop.git
    branch: gh-pages
    username: {{github-username}}
    password: {{github-password}}

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: v31